[package]
name = "wordle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = { version = "0.16.2", features = ["rayon"] }
rayon = "1.5.1"
reedline = "0.2.0"
text_io = "0.1.9"
